/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChampionMasteryV4PeriodChampionMasteryDto : This object contains single Champion Mastery information for player and champion combination.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChampionMasteryV4PeriodChampionMasteryDto {
    /// Number of points needed to achieve next level. Zero if player reached maximum champion level for this champion.
    #[serde(rename = "championPointsUntilNextLevel")]
    pub champion_points_until_next_level: i64,
    /// Is chest granted for this champion or not in current season.
    #[serde(rename = "chestGranted")]
    pub chest_granted: bool,
    /// Champion ID for this entry.
    #[serde(rename = "championId")]
    pub champion_id: i64,
    /// Last time this champion was played by this player - in Unix milliseconds time format.
    #[serde(rename = "lastPlayTime")]
    pub last_play_time: i64,
    /// Champion level for specified player and champion combination.
    #[serde(rename = "championLevel")]
    pub champion_level: i32,
    /// Summoner ID for this entry. (Encrypted)
    #[serde(rename = "summonerId")]
    pub summoner_id: String,
    /// Total number of champion points for this player and champion combination - they are used to determine championLevel.
    #[serde(rename = "championPoints")]
    pub champion_points: i32,
    /// Number of points earned since current level has been achieved.
    #[serde(rename = "championPointsSinceLastLevel")]
    pub champion_points_since_last_level: i64,
    /// The token earned for this champion at the current championLevel. When the championLevel is advanced the tokensEarned resets to 0.
    #[serde(rename = "tokensEarned")]
    pub tokens_earned: i32,
}

impl ChampionMasteryV4PeriodChampionMasteryDto {
    /// This object contains single Champion Mastery information for player and champion combination.
    pub fn new(champion_points_until_next_level: i64, chest_granted: bool, champion_id: i64, last_play_time: i64, champion_level: i32, summoner_id: String, champion_points: i32, champion_points_since_last_level: i64, tokens_earned: i32) -> ChampionMasteryV4PeriodChampionMasteryDto {
        ChampionMasteryV4PeriodChampionMasteryDto {
            champion_points_until_next_level,
            chest_granted,
            champion_id,
            last_play_time,
            champion_level,
            summoner_id,
            champion_points,
            champion_points_since_last_level,
            tokens_earned,
        }
    }
}


