/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LeagueV4PeriodLeagueItemDto {
    #[serde(rename = "freshBlood")]
    pub fresh_blood: bool,
    /// Winning team on Summoners Rift.
    #[serde(rename = "wins")]
    pub wins: i32,
    #[serde(rename = "summonerName")]
    pub summoner_name: String,
    #[serde(rename = "miniSeries", skip_serializing_if = "Option::is_none")]
    pub mini_series: Option<Box<crate::models::LeagueV4PeriodMiniSeriesDto>>,
    #[serde(rename = "inactive")]
    pub inactive: bool,
    #[serde(rename = "veteran")]
    pub veteran: bool,
    #[serde(rename = "hotStreak")]
    pub hot_streak: bool,
    #[serde(rename = "rank")]
    pub rank: String,
    #[serde(rename = "leaguePoints")]
    pub league_points: i32,
    /// Losing team on Summoners Rift.
    #[serde(rename = "losses")]
    pub losses: i32,
    /// Player's encrypted summonerId.
    #[serde(rename = "summonerId")]
    pub summoner_id: String,
}

impl LeagueV4PeriodLeagueItemDto {
    pub fn new(fresh_blood: bool, wins: i32, summoner_name: String, inactive: bool, veteran: bool, hot_streak: bool, rank: String, league_points: i32, losses: i32, summoner_id: String) -> LeagueV4PeriodLeagueItemDto {
        LeagueV4PeriodLeagueItemDto {
            fresh_blood,
            wins,
            summoner_name,
            mini_series: None,
            inactive,
            veteran,
            hot_streak,
            rank,
            league_points,
            losses,
            summoner_id,
        }
    }
}


