/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LolStatusV4PeriodStatusDto {
    #[serde(rename = "id")]
    pub id: i32,
    /// (Legal values:  scheduled,  in_progress,  complete)
    #[serde(rename = "maintenance_status", skip_serializing_if = "Option::is_none")]
    pub maintenance_status: Option<MaintenanceStatus>,
    /// (Legal values:  info,  warning,  critical)
    #[serde(rename = "incident_severity", skip_serializing_if = "Option::is_none")]
    pub incident_severity: Option<IncidentSeverity>,
    #[serde(rename = "titles")]
    pub titles: Vec<crate::models::LolStatusV4PeriodContentDto>,
    #[serde(rename = "updates")]
    pub updates: Vec<crate::models::LolStatusV4PeriodUpdateDto>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "archive_at", skip_serializing_if = "Option::is_none")]
    pub archive_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// (Legal values: windows, macos, android, ios, ps4, xbone, switch)
    #[serde(rename = "platforms")]
    pub platforms: Vec<Platforms>,
}

impl LolStatusV4PeriodStatusDto {
    pub fn new(
        id: i32,
        titles: Vec<crate::models::LolStatusV4PeriodContentDto>,
        updates: Vec<crate::models::LolStatusV4PeriodUpdateDto>,
        created_at: String,
        platforms: Vec<Platforms>,
    ) -> LolStatusV4PeriodStatusDto {
        LolStatusV4PeriodStatusDto {
            id,
            maintenance_status: None,
            incident_severity: None,
            titles,
            updates,
            created_at,
            archive_at: None,
            updated_at: None,
            platforms,
        }
    }
}

/// (Legal values:  scheduled,  in_progress,  complete)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaintenanceStatus {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "complete")]
    Complete,
}

impl Default for MaintenanceStatus {
    fn default() -> MaintenanceStatus {
        Self::Scheduled
    }
}
/// (Legal values:  info,  warning,  critical)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

impl Default for IncidentSeverity {
    fn default() -> IncidentSeverity {
        Self::Info
    }
}
/// (Legal values: windows, macos, android, ios, ps4, xbone, switch)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platforms {}
