/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LorMatchV1PeriodInfoDto {
    /// (Legal values:  Constructed,  Expeditions,  Tutorial)
    #[serde(rename = "game_mode")]
    pub game_mode: GameMode,
    /// (Legal values:  Ranked,  Normal,  AI,  Tutorial,  VanillaTrial,  Singleton,  StandardGauntlet)
    #[serde(rename = "game_type")]
    pub game_type: GameType,
    #[serde(rename = "game_start_time_utc")]
    pub game_start_time_utc: String,
    #[serde(rename = "game_version")]
    pub game_version: String,
    #[serde(rename = "players")]
    pub players: Vec<crate::models::LorMatchV1PeriodPlayerDto>,
    /// Total turns taken by both players.
    #[serde(rename = "total_turn_count")]
    pub total_turn_count: i32,
}

impl LorMatchV1PeriodInfoDto {
    pub fn new(game_mode: GameMode, game_type: GameType, game_start_time_utc: String, game_version: String, players: Vec<crate::models::LorMatchV1PeriodPlayerDto>, total_turn_count: i32) -> LorMatchV1PeriodInfoDto {
        LorMatchV1PeriodInfoDto {
            game_mode,
            game_type,
            game_start_time_utc,
            game_version,
            players,
            total_turn_count,
        }
    }
}

/// (Legal values:  Constructed,  Expeditions,  Tutorial)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GameMode {
    #[serde(rename = "Constructed")]
    Constructed,
    #[serde(rename = "Expeditions")]
    Expeditions,
    #[serde(rename = "Tutorial")]
    Tutorial,
}

impl Default for GameMode {
    fn default() -> GameMode {
        Self::Constructed
    }
}
/// (Legal values:  Ranked,  Normal,  AI,  Tutorial,  VanillaTrial,  Singleton,  StandardGauntlet)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GameType {
    #[serde(rename = "Ranked")]
    Ranked,
    #[serde(rename = "Normal")]
    Normal,
    #[serde(rename = "AI")]
    Ai,
    #[serde(rename = "Tutorial")]
    Tutorial,
    #[serde(rename = "VanillaTrial")]
    VanillaTrial,
    #[serde(rename = "Singleton")]
    Singleton,
    #[serde(rename = "StandardGauntlet")]
    StandardGauntlet,
}

impl Default for GameType {
    fn default() -> GameType {
        Self::Ranked
    }
}

