/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LorMatchV1PeriodPlayerDto {
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "deck_id")]
    pub deck_id: String,
    /// Code for the deck played. Refer to LOR documentation for details on deck codes.
    #[serde(rename = "deck_code")]
    pub deck_code: String,
    #[serde(rename = "factions")]
    pub factions: Vec<String>,
    #[serde(rename = "game_outcome")]
    pub game_outcome: String,
    /// The order in which the players took turns.
    #[serde(rename = "order_of_play")]
    pub order_of_play: i32,
}

impl LorMatchV1PeriodPlayerDto {
    pub fn new(puuid: String, deck_id: String, deck_code: String, factions: Vec<String>, game_outcome: String, order_of_play: i32) -> LorMatchV1PeriodPlayerDto {
        LorMatchV1PeriodPlayerDto {
            puuid,
            deck_id,
            deck_code,
            factions,
            game_outcome,
            order_of_play,
        }
    }
}


