/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MatchV5PeriodMatchTimelineInfoFrameParticipantFrameDamageStats {
    #[serde(rename = "magicDamageDone")]
    pub magic_damage_done: i32,
    #[serde(rename = "magicDamageDoneToChampions")]
    pub magic_damage_done_to_champions: i32,
    #[serde(rename = "magicDamageTaken")]
    pub magic_damage_taken: i32,
    #[serde(rename = "physicalDamageDone")]
    pub physical_damage_done: i32,
    #[serde(rename = "physicalDamageDoneToChampions")]
    pub physical_damage_done_to_champions: i32,
    #[serde(rename = "physicalDamageTaken")]
    pub physical_damage_taken: i32,
    #[serde(rename = "totalDamageDone")]
    pub total_damage_done: i32,
    #[serde(rename = "totalDamageDoneToChampions")]
    pub total_damage_done_to_champions: i32,
    #[serde(rename = "totalDamageTaken")]
    pub total_damage_taken: i32,
    #[serde(rename = "trueDamageDone")]
    pub true_damage_done: i32,
    #[serde(rename = "trueDamageDoneToChampions")]
    pub true_damage_done_to_champions: i32,
    #[serde(rename = "trueDamageTaken")]
    pub true_damage_taken: i32,
}

impl MatchV5PeriodMatchTimelineInfoFrameParticipantFrameDamageStats {
    pub fn new(magic_damage_done: i32, magic_damage_done_to_champions: i32, magic_damage_taken: i32, physical_damage_done: i32, physical_damage_done_to_champions: i32, physical_damage_taken: i32, total_damage_done: i32, total_damage_done_to_champions: i32, total_damage_taken: i32, true_damage_done: i32, true_damage_done_to_champions: i32, true_damage_taken: i32) -> MatchV5PeriodMatchTimelineInfoFrameParticipantFrameDamageStats {
        MatchV5PeriodMatchTimelineInfoFrameParticipantFrameDamageStats {
            magic_damage_done,
            magic_damage_done_to_champions,
            magic_damage_taken,
            physical_damage_done,
            physical_damage_done_to_champions,
            physical_damage_taken,
            total_damage_done,
            total_damage_done_to_champions,
            total_damage_taken,
            true_damage_done,
            true_damage_done_to_champions,
            true_damage_taken,
        }
    }
}


