/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MatchV5PeriodMatchTimelineInfoFrameParticipantFrames {
    #[serde(rename = "1")]
    pub param_1: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "2")]
    pub param_2: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "3")]
    pub param_3: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "4")]
    pub param_4: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "5")]
    pub param_5: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "6")]
    pub param_6: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "7")]
    pub param_7: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "8")]
    pub param_8: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "9")]
    pub param_9: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
    #[serde(rename = "10")]
    pub param_10: Box<crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame>,
}

impl MatchV5PeriodMatchTimelineInfoFrameParticipantFrames {
    pub fn new(param_1: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_2: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_3: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_4: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_5: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_6: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_7: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_8: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_9: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame, param_10: crate::models::MatchV5PeriodMatchTimelineInfoFrameParticipantFrame) -> MatchV5PeriodMatchTimelineInfoFrameParticipantFrames {
        MatchV5PeriodMatchTimelineInfoFrameParticipantFrames {
            param_1: Box::new(param_1),
            param_2: Box::new(param_2),
            param_3: Box::new(param_3),
            param_4: Box::new(param_4),
            param_5: Box::new(param_5),
            param_6: Box::new(param_6),
            param_7: Box::new(param_7),
            param_8: Box::new(param_8),
            param_9: Box::new(param_9),
            param_10: Box::new(param_10),
        }
    }
}


