/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MatchV5PeriodMatchTimelineInfoFrameEventVictimDamageDealt {
    #[serde(rename = "basic")]
    pub basic: bool,
    #[serde(rename = "magicDamage")]
    pub magic_damage: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "participantId")]
    pub participant_id: i32,
    #[serde(rename = "physicalDamage")]
    pub physical_damage: i32,
    #[serde(rename = "spellName")]
    pub spell_name: String,
    #[serde(rename = "spellSlot")]
    pub spell_slot: i32,
    #[serde(rename = "trueDamage")]
    pub true_damage: i32,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MatchV5PeriodMatchTimelineInfoFrameEventVictimDamageDealt {
    pub fn new(basic: bool, magic_damage: i32, name: String, participant_id: i32, physical_damage: i32, spell_name: String, spell_slot: i32, true_damage: i32, r#type: String) -> MatchV5PeriodMatchTimelineInfoFrameEventVictimDamageDealt {
        MatchV5PeriodMatchTimelineInfoFrameEventVictimDamageDealt {
            basic,
            magic_damage,
            name,
            participant_id,
            physical_damage,
            spell_name,
            spell_slot,
            true_damage,
            r#type,
        }
    }
}


