/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MatchV5PeriodObjectivesDto {
    #[serde(rename = "baron")]
    pub baron: Box<crate::models::MatchV5PeriodObjectiveDto>,
    #[serde(rename = "champion")]
    pub champion: Box<crate::models::MatchV5PeriodObjectiveDto>,
    #[serde(rename = "dragon")]
    pub dragon: Box<crate::models::MatchV5PeriodObjectiveDto>,
    #[serde(rename = "inhibitor")]
    pub inhibitor: Box<crate::models::MatchV5PeriodObjectiveDto>,
    #[serde(rename = "riftHerald")]
    pub rift_herald: Box<crate::models::MatchV5PeriodObjectiveDto>,
    #[serde(rename = "tower")]
    pub tower: Box<crate::models::MatchV5PeriodObjectiveDto>,
}

impl MatchV5PeriodObjectivesDto {
    pub fn new(baron: crate::models::MatchV5PeriodObjectiveDto, champion: crate::models::MatchV5PeriodObjectiveDto, dragon: crate::models::MatchV5PeriodObjectiveDto, inhibitor: crate::models::MatchV5PeriodObjectiveDto, rift_herald: crate::models::MatchV5PeriodObjectiveDto, tower: crate::models::MatchV5PeriodObjectiveDto) -> MatchV5PeriodObjectivesDto {
        MatchV5PeriodObjectivesDto {
            baron: Box::new(baron),
            champion: Box::new(champion),
            dragon: Box::new(dragon),
            inhibitor: Box::new(inhibitor),
            rift_herald: Box::new(rift_herald),
            tower: Box::new(tower),
        }
    }
}


