/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpectatorV4PeriodCurrentGameInfo {
    /// The ID of the game
    #[serde(rename = "gameId")]
    pub game_id: i64,
    /// The game type
    #[serde(rename = "gameType")]
    pub game_type: String,
    /// The game start time represented in epoch milliseconds
    #[serde(rename = "gameStartTime")]
    pub game_start_time: i64,
    /// The ID of the map
    #[serde(rename = "mapId")]
    pub map_id: i64,
    /// The amount of time in seconds that has passed since the game started
    #[serde(rename = "gameLength")]
    pub game_length: i64,
    /// The ID of the platform on which the game is being played
    #[serde(rename = "platformId")]
    pub platform_id: String,
    /// The game mode
    #[serde(rename = "gameMode")]
    pub game_mode: String,
    /// Banned champion information
    #[serde(rename = "bannedChampions")]
    pub banned_champions: Vec<crate::models::SpectatorV4PeriodBannedChampion>,
    /// The queue type (queue types are documented on the Game Constants page)
    #[serde(rename = "gameQueueConfigId", skip_serializing_if = "Option::is_none")]
    pub game_queue_config_id: Option<i64>,
    #[serde(rename = "observers")]
    pub observers: Box<crate::models::SpectatorV4PeriodObserver>,
    /// The participant information
    #[serde(rename = "participants")]
    pub participants: Vec<crate::models::SpectatorV4PeriodCurrentGameParticipant>,
}

impl SpectatorV4PeriodCurrentGameInfo {
    pub fn new(game_id: i64, game_type: String, game_start_time: i64, map_id: i64, game_length: i64, platform_id: String, game_mode: String, banned_champions: Vec<crate::models::SpectatorV4PeriodBannedChampion>, observers: crate::models::SpectatorV4PeriodObserver, participants: Vec<crate::models::SpectatorV4PeriodCurrentGameParticipant>) -> SpectatorV4PeriodCurrentGameInfo {
        SpectatorV4PeriodCurrentGameInfo {
            game_id,
            game_type,
            game_start_time,
            map_id,
            game_length,
            platform_id,
            game_mode,
            banned_champions,
            game_queue_config_id: None,
            observers: Box::new(observers),
            participants,
        }
    }
}


