/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpectatorV4PeriodCurrentGameParticipant {
    /// The ID of the champion played by this participant
    #[serde(rename = "championId")]
    pub champion_id: i64,
    #[serde(rename = "perks", skip_serializing_if = "Option::is_none")]
    pub perks: Option<Box<crate::models::SpectatorV4PeriodPerks>>,
    /// The ID of the profile icon used by this participant
    #[serde(rename = "profileIconId")]
    pub profile_icon_id: i64,
    /// Flag indicating whether or not this participant is a bot
    #[serde(rename = "bot")]
    pub bot: bool,
    /// The team ID of this participant, indicating the participant's team
    #[serde(rename = "teamId")]
    pub team_id: i64,
    /// The summoner name of this participant
    #[serde(rename = "summonerName")]
    pub summoner_name: String,
    /// The encrypted summoner ID of this participant
    #[serde(rename = "summonerId")]
    pub summoner_id: String,
    /// The ID of the first summoner spell used by this participant
    #[serde(rename = "spell1Id")]
    pub spell1_id: i64,
    /// The ID of the second summoner spell used by this participant
    #[serde(rename = "spell2Id")]
    pub spell2_id: i64,
    /// List of Game Customizations
    #[serde(rename = "gameCustomizationObjects")]
    pub game_customization_objects: Vec<crate::models::SpectatorV4PeriodGameCustomizationObject>,
}

impl SpectatorV4PeriodCurrentGameParticipant {
    pub fn new(champion_id: i64, profile_icon_id: i64, bot: bool, team_id: i64, summoner_name: String, summoner_id: String, spell1_id: i64, spell2_id: i64, game_customization_objects: Vec<crate::models::SpectatorV4PeriodGameCustomizationObject>) -> SpectatorV4PeriodCurrentGameParticipant {
        SpectatorV4PeriodCurrentGameParticipant {
            champion_id,
            perks: None,
            profile_icon_id,
            bot,
            team_id,
            summoner_name,
            summoner_id,
            spell1_id,
            spell2_id,
            game_customization_objects,
        }
    }
}


