/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SummonerV4PeriodSummonerDto : represents a summoner



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SummonerV4PeriodSummonerDto {
    /// Encrypted account ID. Max length 56 characters.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// ID of the summoner icon associated with the summoner.
    #[serde(rename = "profileIconId")]
    pub profile_icon_id: i32,
    /// Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change
    #[serde(rename = "revisionDate")]
    pub revision_date: i64,
    /// Summoner name.
    #[serde(rename = "name")]
    pub name: String,
    /// Encrypted summoner ID. Max length 63 characters.
    #[serde(rename = "id")]
    pub id: String,
    /// Encrypted PUUID. Exact length of 78 characters.
    #[serde(rename = "puuid")]
    pub puuid: String,
    /// Summoner level associated with the summoner.
    #[serde(rename = "summonerLevel")]
    pub summoner_level: i64,
}

impl SummonerV4PeriodSummonerDto {
    /// represents a summoner
    pub fn new(account_id: String, profile_icon_id: i32, revision_date: i64, name: String, id: String, puuid: String, summoner_level: i64) -> SummonerV4PeriodSummonerDto {
        SummonerV4PeriodSummonerDto {
            account_id,
            profile_icon_id,
            revision_date,
            name,
            id,
            puuid,
            summoner_level,
        }
    }
}


