/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TftMatchV1PeriodInfoDto {
    /// Unix timestamp.
    #[serde(rename = "game_datetime")]
    pub game_datetime: i64,
    /// Game length in seconds.
    #[serde(rename = "game_length")]
    pub game_length: f32,
    /// Game variation key. Game variations documented in TFT static data.
    #[serde(rename = "game_variation", skip_serializing_if = "Option::is_none")]
    pub game_variation: Option<String>,
    /// Game client version.
    #[serde(rename = "game_version")]
    pub game_version: String,
    #[serde(rename = "participants")]
    pub participants: Vec<crate::models::TftMatchV1PeriodParticipantDto>,
    /// Please refer to the League of Legends documentation.
    #[serde(rename = "queue_id")]
    pub queue_id: i32,
    /// Teamfight Tactics set number.
    #[serde(rename = "tft_set_number")]
    pub tft_set_number: i32,
}

impl TftMatchV1PeriodInfoDto {
    pub fn new(game_datetime: i64, game_length: f32, game_version: String, participants: Vec<crate::models::TftMatchV1PeriodParticipantDto>, queue_id: i32, tft_set_number: i32) -> TftMatchV1PeriodInfoDto {
        TftMatchV1PeriodInfoDto {
            game_datetime,
            game_length,
            game_variation: None,
            game_version,
            participants,
            queue_id,
            tft_set_number,
        }
    }
}


