/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TftLeagueV1PeriodTopRatedLadderEntryDto {
    #[serde(rename = "summonerId")]
    pub summoner_id: String,
    #[serde(rename = "summonerName")]
    pub summoner_name: String,
    /// (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
    #[serde(rename = "ratedTier")]
    pub rated_tier: RatedTier,
    #[serde(rename = "ratedRating")]
    pub rated_rating: i32,
    /// First placement.
    #[serde(rename = "wins")]
    pub wins: i32,
    #[serde(rename = "previousUpdateLadderPosition")]
    pub previous_update_ladder_position: i32,
}

impl TftLeagueV1PeriodTopRatedLadderEntryDto {
    pub fn new(summoner_id: String, summoner_name: String, rated_tier: RatedTier, rated_rating: i32, wins: i32, previous_update_ladder_position: i32) -> TftLeagueV1PeriodTopRatedLadderEntryDto {
        TftLeagueV1PeriodTopRatedLadderEntryDto {
            summoner_id,
            summoner_name,
            rated_tier,
            rated_rating,
            wins,
            previous_update_ladder_position,
        }
    }
}

/// (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RatedTier {
    #[serde(rename = "ORANGE")]
    Orange,
    #[serde(rename = "PURPLE")]
    Purple,
    #[serde(rename = "BLUE")]
    Blue,
    #[serde(rename = "GREEN")]
    Green,
    #[serde(rename = "GRAY")]
    Gray,
}

impl Default for RatedTier {
    fn default() -> RatedTier {
        Self::Orange
    }
}

