/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TftLeagueV1PeriodLeagueEntryDto {
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "leagueId", skip_serializing_if = "Option::is_none")]
    pub league_id: Option<String>,
    /// Player's encrypted summonerId.
    #[serde(rename = "summonerId")]
    pub summoner_id: String,
    #[serde(rename = "summonerName")]
    pub summoner_name: String,
    #[serde(rename = "queueType")]
    pub queue_type: String,
    /// Only included for the RANKED_TFT_TURBO queueType.              (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
    #[serde(rename = "ratedTier", skip_serializing_if = "Option::is_none")]
    pub rated_tier: Option<RatedTier>,
    /// Only included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "ratedRating", skip_serializing_if = "Option::is_none")]
    pub rated_rating: Option<i32>,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    /// A player's division within a tier. Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<String>,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "leaguePoints", skip_serializing_if = "Option::is_none")]
    pub league_points: Option<i32>,
    /// First placement.
    #[serde(rename = "wins")]
    pub wins: i32,
    /// Second through eighth placement.
    #[serde(rename = "losses")]
    pub losses: i32,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "hotStreak", skip_serializing_if = "Option::is_none")]
    pub hot_streak: Option<bool>,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "veteran", skip_serializing_if = "Option::is_none")]
    pub veteran: Option<bool>,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "freshBlood", skip_serializing_if = "Option::is_none")]
    pub fresh_blood: Option<bool>,
    /// Not included for the RANKED_TFT_TURBO queueType.
    #[serde(rename = "inactive", skip_serializing_if = "Option::is_none")]
    pub inactive: Option<bool>,
    #[serde(rename = "miniSeries", skip_serializing_if = "Option::is_none")]
    pub mini_series: Option<Box<crate::models::TftLeagueV1PeriodMiniSeriesDto>>,
}

impl TftLeagueV1PeriodLeagueEntryDto {
    pub fn new(summoner_id: String, summoner_name: String, queue_type: String, wins: i32, losses: i32) -> TftLeagueV1PeriodLeagueEntryDto {
        TftLeagueV1PeriodLeagueEntryDto {
            league_id: None,
            summoner_id,
            summoner_name,
            queue_type,
            rated_tier: None,
            rated_rating: None,
            tier: None,
            rank: None,
            league_points: None,
            wins,
            losses,
            hot_streak: None,
            veteran: None,
            fresh_blood: None,
            inactive: None,
            mini_series: None,
        }
    }
}

/// Only included for the RANKED_TFT_TURBO queueType.              (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RatedTier {
    #[serde(rename = "ORANGE")]
    Orange,
    #[serde(rename = "PURPLE")]
    Purple,
    #[serde(rename = "BLUE")]
    Blue,
    #[serde(rename = "GREEN")]
    Green,
    #[serde(rename = "GRAY")]
    Gray,
}

impl Default for RatedTier {
    fn default() -> RatedTier {
        Self::Orange
    }
}

