/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValContentV1PeriodLocalizedNamesDto {
    #[serde(rename = "ar-AE")]
    pub ar_ae: String,
    #[serde(rename = "de-DE")]
    pub de_de: String,
    #[serde(rename = "en-GB", skip_serializing_if = "Option::is_none")]
    pub en_gb: Option<String>,
    #[serde(rename = "en-US")]
    pub en_us: String,
    #[serde(rename = "es-ES")]
    pub es_es: String,
    #[serde(rename = "es-MX")]
    pub es_mx: String,
    #[serde(rename = "fr-FR")]
    pub fr_fr: String,
    #[serde(rename = "id-ID")]
    pub id_id: String,
    #[serde(rename = "it-IT")]
    pub it_it: String,
    #[serde(rename = "ja-JP")]
    pub ja_jp: String,
    #[serde(rename = "ko-KR")]
    pub ko_kr: String,
    #[serde(rename = "pl-PL")]
    pub pl_pl: String,
    #[serde(rename = "pt-BR")]
    pub pt_br: String,
    #[serde(rename = "ru-RU")]
    pub ru_ru: String,
    #[serde(rename = "th-TH")]
    pub th_th: String,
    #[serde(rename = "tr-TR")]
    pub tr_tr: String,
    #[serde(rename = "vi-VN")]
    pub vi_vn: String,
    #[serde(rename = "zh-CN")]
    pub zh_cn: String,
    #[serde(rename = "zh-TW")]
    pub zh_tw: String,
}

impl ValContentV1PeriodLocalizedNamesDto {
    pub fn new(ar_ae: String, de_de: String, en_us: String, es_es: String, es_mx: String, fr_fr: String, id_id: String, it_it: String, ja_jp: String, ko_kr: String, pl_pl: String, pt_br: String, ru_ru: String, th_th: String, tr_tr: String, vi_vn: String, zh_cn: String, zh_tw: String) -> ValContentV1PeriodLocalizedNamesDto {
        ValContentV1PeriodLocalizedNamesDto {
            ar_ae,
            de_de,
            en_gb: None,
            en_us,
            es_es,
            es_mx,
            fr_fr,
            id_id,
            it_it,
            ja_jp,
            ko_kr,
            pl_pl,
            pt_br,
            ru_ru,
            th_th,
            tr_tr,
            vi_vn,
            zh_cn,
            zh_tw,
        }
    }
}


