/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValMatchV1PeriodPlayerDto {
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "gameName")]
    pub game_name: String,
    #[serde(rename = "tagLine")]
    pub tag_line: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "partyId")]
    pub party_id: String,
    #[serde(rename = "characterId")]
    pub character_id: String,
    #[serde(rename = "stats")]
    pub stats: Box<crate::models::ValMatchV1PeriodPlayerStatsDto>,
    #[serde(rename = "competitiveTier")]
    pub competitive_tier: i32,
    #[serde(rename = "playerCard")]
    pub player_card: String,
    #[serde(rename = "playerTitle")]
    pub player_title: String,
}

impl ValMatchV1PeriodPlayerDto {
    pub fn new(puuid: String, game_name: String, tag_line: String, team_id: String, party_id: String, character_id: String, stats: crate::models::ValMatchV1PeriodPlayerStatsDto, competitive_tier: i32, player_card: String, player_title: String) -> ValMatchV1PeriodPlayerDto {
        ValMatchV1PeriodPlayerDto {
            puuid,
            game_name,
            tag_line,
            team_id,
            party_id,
            character_id,
            stats: Box::new(stats),
            competitive_tier,
            player_card,
            player_title,
        }
    }
}


