/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValMatchV1PeriodMatchDto {
    #[serde(rename = "matchInfo")]
    pub match_info: Box<crate::models::ValMatchV1PeriodMatchInfoDto>,
    #[serde(rename = "players")]
    pub players: Vec<crate::models::ValMatchV1PeriodPlayerDto>,
    #[serde(rename = "coaches")]
    pub coaches: Vec<crate::models::ValMatchV1PeriodCoachDto>,
    #[serde(rename = "teams")]
    pub teams: Vec<crate::models::ValMatchV1PeriodTeamDto>,
    #[serde(rename = "roundResults")]
    pub round_results: Vec<crate::models::ValMatchV1PeriodRoundResultDto>,
}

impl ValMatchV1PeriodMatchDto {
    pub fn new(match_info: crate::models::ValMatchV1PeriodMatchInfoDto, players: Vec<crate::models::ValMatchV1PeriodPlayerDto>, coaches: Vec<crate::models::ValMatchV1PeriodCoachDto>, teams: Vec<crate::models::ValMatchV1PeriodTeamDto>, round_results: Vec<crate::models::ValMatchV1PeriodRoundResultDto>) -> ValMatchV1PeriodMatchDto {
        ValMatchV1PeriodMatchDto {
            match_info: Box::new(match_info),
            players,
            coaches,
            teams,
            round_results,
        }
    }
}


