/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValRankedV1PeriodPlayerDto {
    /// This field may be omitted if the player has been anonymized.
    #[serde(rename = "puuid", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
    /// This field may be omitted if the player has been anonymized.
    #[serde(rename = "gameName", skip_serializing_if = "Option::is_none")]
    pub game_name: Option<String>,
    /// This field may be omitted if the player has been anonymized.
    #[serde(rename = "tagLine", skip_serializing_if = "Option::is_none")]
    pub tag_line: Option<String>,
    #[serde(rename = "leaderboardRank")]
    pub leaderboard_rank: i64,
    #[serde(rename = "rankedRating")]
    pub ranked_rating: i64,
    #[serde(rename = "numberOfWins")]
    pub number_of_wins: i64,
    #[serde(rename = "competitiveTier", skip_serializing_if = "Option::is_none")]
    pub competitive_tier: Option<i64>,
}

impl ValRankedV1PeriodPlayerDto {
    pub fn new(leaderboard_rank: i64, ranked_rating: i64, number_of_wins: i64) -> ValRankedV1PeriodPlayerDto {
        ValRankedV1PeriodPlayerDto {
            puuid: None,
            game_name: None,
            tag_line: None,
            leaderboard_rank,
            ranked_rating,
            number_of_wins,
            competitive_tier: None,
        }
    }
}


