/*
 * Riot API
 *
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: dae26e2703c82eb19447d1b27f1209801cb83beb
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValMatchV1PeriodMatchInfoDto {
    #[serde(rename = "matchId")]
    pub match_id: String,
    #[serde(rename = "mapId")]
    pub map_id: String,
    #[serde(rename = "gameLengthMillis")]
    pub game_length_millis: i32,
    #[serde(rename = "gameStartMillis")]
    pub game_start_millis: i64,
    #[serde(rename = "provisioningFlowId")]
    pub provisioning_flow_id: String,
    #[serde(rename = "isCompleted")]
    pub is_completed: bool,
    #[serde(rename = "customGameName")]
    pub custom_game_name: String,
    #[serde(rename = "queueId")]
    pub queue_id: String,
    #[serde(rename = "gameMode")]
    pub game_mode: String,
    #[serde(rename = "isRanked")]
    pub is_ranked: bool,
    #[serde(rename = "seasonId")]
    pub season_id: String,
}

impl ValMatchV1PeriodMatchInfoDto {
    pub fn new(match_id: String, map_id: String, game_length_millis: i32, game_start_millis: i64, provisioning_flow_id: String, is_completed: bool, custom_game_name: String, queue_id: String, game_mode: String, is_ranked: bool, season_id: String) -> ValMatchV1PeriodMatchInfoDto {
        ValMatchV1PeriodMatchInfoDto {
            match_id,
            map_id,
            game_length_millis,
            game_start_millis,
            provisioning_flow_id,
            is_completed,
            custom_game_name,
            queue_id,
            game_mode,
            is_ranked,
            season_id,
        }
    }
}


